### ISSUE TITLE
Can't get all section names from big ini file

### ISSUE THREAD

**Issue by Po-temkin** [lipkau/PsIni#76]
I think that I found certain bug.
I have quite big ini file and when I trying to get names of all Sections I see Keys names of fist Section instead of it.
```
PS C:\Windows\system32> (Get-IniContent -FilePath 'C:\Users\admin\Desktop\indexes.txt').Keys

Name                           Value
----                           -----
coldPath                       $SPLUNK_DB\$_index_name\colddb
coldToFrozenDir
enableDataIntegrityControl     0
enableTsidxReduction           0
frozenTimePeriodInSecs         2678400
homePath                       $SPLUNK_DB\$_index_name\db
maxTotalDataSizeMB             512000
thawedPath                     $SPLUNK_DB\$_index_name\thaweddb
timePeriodInSecBeforeTsidxR...
tsidxReductionCheckPeriodInSec
repFactor                      auto
```

[indexes.txt](https://github.com/lipkau/PsIni/files/11068633/indexes.txt)

**Comment by CanMonster** [comment]
Hi Po-temkin,

I have had a quick look and I can see what the issue is. I am not sure what the fix is but I can tell you that the issue is not relate to the size of the INI but rather there looks to be a "Keyword" conflict between the content of your Indexes.ini file and the Ordered Dictionary the Get-IniContent function creates. 

The Get-IniContent function creates an Order Dictionary which has two properties, Keys and Values. The function uses the [Section Name] as the Key and the values are the key = value pairs beneath each. 

Ordered Dictionary
Key = "[Section]"
Values = An array of the "Key = value" pairs beneath each section

Your Index.txt file contains a Section named [keys], i.e.

[keys]
coldPath = $SPLUNK_DB\$_index_name\colddb
coldToFrozenDir = 
enableDataIntegrityControl = 0
enableTsidxReduction = 0
frozenTimePeriodInSecs = 2678400
homePath = $SPLUNK_DB\$_index_name\db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB\$_index_name\thaweddb
timePeriodInSecBeforeTsidxReduction = 
tsidxReductionCheckPeriodInSec = 
repFactor = auto

The [keys] section is conflicting with the "Keys" property of the Ordered Dictionary.

So, if you rename or remove the [keys] section the Get-IniContent function works as expected. This is the immediate fix. The long term fix would be to update the function to treat sections with the name [keys] or [values] as a literal string or something similar to avoid the keyword conflict.

**Comment by CanMonster** [comment]
Hi Po-temkin,

Some further research has shown that this is an known and open issue.

https://github.com/PowerShell/PowerShell/issues/7758

The simplest solution to avoid the keyword conflict is to instead use:

(Get-IniContent -FilePath 'C:\Users\admin\Desktop\indexes.txt').PSBase.Keys

Hope this helps.

**Comment by Po-temkin** [comment]
Thank you for helpful advice, its works.

> Hi Po-temkin,
> 
> Some further research has shown that this is an known and open issue.
> 
> [PowerShell/PowerShell#7758](https://github.com/PowerShell/PowerShell/issues/7758)
> 
> The simplest solution to avoid the keyword conflict is to instead use:
> 
> (Get-IniContent -FilePath 'C:\Users\admin\Desktop\indexes.txt').PSBase.Keys
> 
> Hope this helps.

Thank you for helpful advice, its works.
